name: PHP Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  php:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "PHP-${{ matrix.php-versions }}: CS/PHPStan/Sample"
    strategy:
      matrix:
        php-versions: ['7.4']
        experimental: [false]
        include:
          - php-versions: 8.0
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: cs2pr, phpcs, phpstan
          extensions: uopz
          ini-values: pcov.directory=ApnsPHP
          coverage: pcov

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run PHPCS
        continue-on-error: false
        run: phpcs -q --report=checkstyle ApnsPHP --standard=PSR12 | cs2pr

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: phpstan analyse ApnsPHP -l0

      - name: Setup sample
        run: |
          touch entrust_root_certification_authority.pem
          touch server_certificates_bundle_sandbox.pem

      - name: Run sample
        run: php sample_push.php | grep "Trying tls://gateway.sandbox.push.apple.com:2195"

      - name: Run PHPUnit
        run: vendor/bin/phpunit -c phpunit.xml --coverage-text